// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL2Cqw-ItHx_nPbcQ1WbMOiWA7irmZt4w',
    appId: '1:851209319492:web:4648f53453ceed5db4f811',
    messagingSenderId: '851209319492',
    projectId: 'uapodcasts-68a04',
    authDomain: 'uapodcasts-68a04.firebaseapp.com',
    storageBucket: 'uapodcasts-68a04.appspot.com',
    measurementId: 'G-ZJ48MVLB9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnI5Z9dgZnrYhf0TRj3wE5bfmmI8wI80g',
    appId: '1:851209319492:android:070e662594fbf2aab4f811',
    messagingSenderId: '851209319492',
    projectId: 'uapodcasts-68a04',
    storageBucket: 'uapodcasts-68a04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBieyDHd15OKb9vGqEtmOQHGyeyYSgSce8',
    appId: '1:851209319492:ios:153d0f9bec19ac88b4f811',
    messagingSenderId: '851209319492',
    projectId: 'uapodcasts-68a04',
    storageBucket: 'uapodcasts-68a04.appspot.com',
    iosBundleId: 'com.podcastsua.podcastsUaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBieyDHd15OKb9vGqEtmOQHGyeyYSgSce8',
    appId: '1:851209319492:ios:c4eb6115857d98ceb4f811',
    messagingSenderId: '851209319492',
    projectId: 'uapodcasts-68a04',
    storageBucket: 'uapodcasts-68a04.appspot.com',
    iosBundleId: 'com.podcastsua.podcastsUaApp.RunnerTests',
  );
}
